from __future__ import annotations

import asyncio
import base64
import hashlib
import inspect
import json
import re
from collections.abc import Awaitable, Callable
from contextlib import asynccontextmanager
from datetime import UTC, datetime
from functools import wraps
from importlib.resources import files
from typing import Annotated, Any, Literal, ParamSpec
from urllib.parse import quote, urlparse
from uuid import uuid4

import uvicorn
from mcp.server import MCPServer
from mcp.server.apps import Apps, ResourceCsp
from mcp.server.mcpserver import Context
from mcp.server.mcpserver.exceptions import ResourceError, ToolError
from mcp.server.transport_security import TransportSecuritySettings
from mcp.types import (
    AudioContent,
    BlobResourceContents,
    CallToolResult,
    EmbeddedResource,
    ResourceLink,
    TextContent,
    ToolAnnotations,
)
from pydantic import Field
from starlette.requests import Request
from starlette.responses import JSONResponse
from starlette.routing import Route

from voxbridge import __version__
from voxbridge.audio_composer import AudioCompositionError, PcmWavComposer, WavSegment
from voxbridge.audio_store import AudioArtifact, AudioArtifactStore
from voxbridge.config import settings
from voxbridge.models import (
    DialogueSegment,
    MaterializedAudioMetadata,
    SpeechDeliveryMetadata,
    SpeechRequest,
    SpeechResult,
)
from voxbridge.providers.base import ProviderError
from voxbridge.registry import REGISTRY, close_registry
from voxbridge.replay_cache import ReplayCache, ReplayCacheCapacityError

_AUDIO_DELIVERY_UI_URI = "ui://voxbridge/audio-delivery-v12.html"
_AUDIO_DELIVERY_UI_HTML = (
    files("voxbridge").joinpath("ui").joinpath("audio-delivery-v1.html").read_text(encoding="utf-8")
)
_apps = Apps()
_apps.add_html_resource(
    _AUDIO_DELIVERY_UI_URI,
    _AUDIO_DELIVERY_UI_HTML,
    name="voxbridge-audio-delivery",
    title="VoxBridge audio delivery",
    description="Play generated VoxBridge audio, download it as a file, or do both.",
    csp=ResourceCsp(connect_domains=[], resource_domains=[]),
    prefers_border=True,
)


@asynccontextmanager
async def _lifespan(_: MCPServer):
    try:
        yield None
    finally:
        _generation_replays.clear()
        _audio_artifacts.clear()
        await close_registry()


mcp = MCPServer(
    "VoxBridge",
    version=__version__,
    instructions=(
        "Provider-neutral text-to-speech. Never switch providers silently. "
        "Generated audio is synthetic. Use delivery='playback', 'file', or 'both' "
        "to choose the returned representation. Use generate_dialogue for an ordered, "
        "single-provider, multi-voice WAV file. To hand generated bytes to a compatible "
        "downstream tool, call materialize_audio_file with the exact "
        "materialize_resource_uri from the generation result. If the host hides that "
        "custom URI, pass the exact generated file_name instead. Never infer or alter "
        "either value."
    ),
    extensions=[_apps],
    lifespan=_lifespan,
    log_level=settings.voxbridge_log_level,
)

_generation_slots = asyncio.Semaphore(settings.voxbridge_max_concurrent_generations)
_audio_artifacts = AudioArtifactStore(
    ttl_seconds=settings.voxbridge_audio_download_ttl_seconds,
    max_items=settings.voxbridge_audio_download_max_items,
    max_bytes=settings.voxbridge_audio_download_max_bytes,
)
_generation_replay_capacity = max(
    1,
    min(
        2,
        settings.voxbridge_audio_download_max_items,
        settings.voxbridge_audio_download_max_bytes // settings.voxbridge_max_audio_bytes,
    ),
)
_generation_replays = ReplayCache[CallToolResult](
    ttl_seconds=min(120, settings.voxbridge_audio_download_ttl_seconds),
    # A delivery result can contain a large base64 playback payload. Two recent
    # results are sufficient for approval retries; the raw artifact-store byte
    # capacity also bounds this value so every cached file link remains live.
    max_items=_generation_replay_capacity,
    max_inflight=settings.voxbridge_max_concurrent_generations,
)

_AUDIO_FILE_TYPES = {
    "audio/aac": ("aac", "aac", "audio/aac"),
    "audio/flac": ("flac", "flac", "audio/flac"),
    "audio/mp3": ("mp3", "mp3", "audio/mpeg"),
    "audio/mp4": ("m4a", "m4a", "audio/mp4"),
    "audio/mpeg": ("mp3", "mp3", "audio/mpeg"),
    "audio/ogg": ("ogg", "ogg", "audio/ogg"),
    "audio/opus": ("opus", "opus", "audio/opus"),
    "audio/vnd.wave": ("wav", "wav", "audio/wav"),
    "audio/wav": ("wav", "wav", "audio/wav"),
    "audio/webm": ("webm", "webm", "audio/webm"),
    "audio/x-flac": ("flac", "flac", "audio/flac"),
    "audio/x-wav": ("wav", "wav", "audio/wav"),
}
_AUDIO_FILE_NAME_PATTERN = re.compile(
    r"^voxbridge-(?P<file_id>[0-9a-f]{32})\.(?P<extension>[a-z0-9]+)$"
)
_P = ParamSpec("_P")


def _reject_nonstandard_json_constant(value: str) -> None:
    raise ValueError(f"Non-standard JSON constant: {value}")


def _audio_file_details(mime_type: str) -> tuple[str, str, str]:
    media_type = mime_type.partition(";")[0].strip().lower()
    details = _AUDIO_FILE_TYPES.get(media_type)
    if details is None:
        raise ToolError(f"Provider returned an unsupported audio media type '{media_type}'")
    return details


def _download_filename(extension: str) -> str:
    return f"voxbridge-{uuid4().hex}.{extension}"


def _resource_uri(format_id: str, token: str, file_name: str) -> str:
    return f"voxbridge://audio/{format_id}/{token}/{file_name}"


def _materialize_resource_uri(file_name: str) -> str:
    match = _AUDIO_FILE_NAME_PATTERN.fullmatch(file_name)
    if match is None:  # pragma: no cover - generated names always use this pattern
        raise ToolError("Generated audio file name cannot be materialized")
    return f"voxbridge://audio/{match.group('file_id')}"


def _read_audio_artifact(
    token: str,
    file_name: str,
    *,
    expected_format: str,
) -> bytes:
    artifact = _audio_artifacts.get(token)
    if artifact is None or artifact.file_name != file_name or artifact.format_id != expected_format:
        raise ResourceError("Audio file is unavailable or has expired")
    return artifact.data


def _artifact_from_resource_uri(resource_uri: str) -> AudioArtifact:
    parsed = urlparse(resource_uri)
    parts = parsed.path.lstrip("/").split("/")
    if parsed.scheme != "voxbridge" or parsed.netloc != "audio" or parsed.query or parsed.fragment:
        raise ToolError("resource_uri is not a valid VoxBridge audio resource")

    if len(parts) == 1 and re.fullmatch(r"[0-9a-f]{32}", parts[0]):
        file_id = parts[0]
        for extension in sorted({details[1] for details in _AUDIO_FILE_TYPES.values()}):
            artifact = _audio_artifacts.get_by_file_name(f"voxbridge-{file_id}.{extension}")
            if artifact is not None:
                return artifact
        raise ToolError("Audio file is unavailable or has expired")

    if len(parts) != 3 or not all(parts):
        raise ToolError("resource_uri is not a valid VoxBridge audio resource")
    format_id, token, file_name = parts
    artifact = _audio_artifacts.get(token)
    if artifact is None or artifact.file_name != file_name or artifact.format_id != format_id:
        raise ToolError("Audio file is unavailable or has expired")
    return artifact


def _artifact_from_file_name(file_name: str) -> AudioArtifact:
    match = _AUDIO_FILE_NAME_PATTERN.fullmatch(file_name)
    supported_extensions = {details[1] for details in _AUDIO_FILE_TYPES.values()}
    if match is None or match.group("extension") not in supported_extensions:
        raise ToolError("file_name is not a valid generated VoxBridge audio file name")
    artifact = _audio_artifacts.get_by_file_name(file_name)
    if artifact is None:
        raise ToolError("Audio file is unavailable or has expired")
    return artifact


def _parse_options_json(options_json: str | None, *, field_name: str = "options_json"):
    if not options_json:
        return {}
    try:
        parsed = json.loads(
            options_json,
            parse_constant=_reject_nonstandard_json_constant,
        )
    except (json.JSONDecodeError, ValueError) as exc:
        raise ToolError(f"{field_name} must contain valid JSON") from exc
    if not isinstance(parsed, dict):
        raise ToolError(f"{field_name} must decode to a JSON object")
    return parsed


def _validate_delivery(delivery: str) -> None:
    if delivery not in {"playback", "file", "both"}:
        raise ToolError("delivery must be 'playback', 'file', or 'both'")


def _request_replay_scope(context: Context | None) -> str:
    if context is not None:
        try:
            meta = context.request_context.meta
        except (AttributeError, ValueError):
            meta = None
        if meta:
            openai_session = meta.get("openai/session")
            if isinstance(openai_session, str) and openai_session:
                return f"openai/session:{openai_session}"

    # The deployed gateway is a private, single-user service with no public
    # domain. Older/non-OpenAI clients may omit request session metadata, so a
    # short-lived private-service scope still protects approval retries without
    # retaining caller data in the key or sharing it with a public tenant.
    return "private-single-user-gateway"


def _generation_replay_key(
    tool_name: str,
    arguments: dict[str, Any],
    context: Context | None,
) -> str:
    normalized = dict(arguments)
    provider = normalized.get("provider")
    if isinstance(provider, str):
        normalized["provider"] = provider.strip().lower()

    if tool_name == "generate_speech":
        output_format = normalized.get("output_format")
        if isinstance(output_format, str):
            normalized["output_format"] = output_format.strip().lower()
        try:
            normalized["options_json"] = _parse_options_json(normalized.get("options_json"))
        except ToolError:
            # Preserve the tool's established validation order. The wrapped
            # call will reject malformed JSON and the failure is not cached.
            pass
    elif tool_name == "generate_dialogue":
        normalized["segments"] = [
            segment.model_dump(mode="json") if isinstance(segment, DialogueSegment) else segment
            for segment in normalized["segments"]
        ]

    canonical = json.dumps(
        {
            "scope": _request_replay_scope(context),
            "tool": tool_name,
            "arguments": normalized,
        },
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _replay_protected(
    tool_name: str,
) -> Callable[
    [Callable[_P, Awaitable[CallToolResult]]],
    Callable[_P, Awaitable[CallToolResult]],
]:
    def decorate(
        function: Callable[_P, Awaitable[CallToolResult]],
    ) -> Callable[_P, Awaitable[CallToolResult]]:
        signature = inspect.signature(function)

        @wraps(function)
        async def wrapped(*args: _P.args, **kwargs: _P.kwargs) -> CallToolResult:
            bound = signature.bind(*args, **kwargs)
            bound.apply_defaults()
            arguments = dict(bound.arguments)
            context = arguments.pop("ctx", None)
            key = _generation_replay_key(tool_name, arguments, context)
            try:
                return await _generation_replays.get_or_create(
                    key,
                    lambda: function(*args, **kwargs),
                )
            except ReplayCacheCapacityError as exc:
                raise ToolError(
                    "VoxBridge is already processing the maximum number of concurrent "
                    "generation requests; retry shortly"
                ) from exc

        return wrapped

    return decorate


def _dialogue_failure_message(
    segment_number: int,
    segment_count: int,
    completed_calls: int,
    attempted_calls: int,
    reason: str,
) -> str:
    return (
        f"Segment {segment_number} of {segment_count} failed after "
        f"{completed_calls} provider call(s) completed ({attempted_calls} attempted): {reason}. "
        "Provider charges may already apply; no combined audio file was stored."
    )


@mcp.resource(
    "voxbridge://audio/mp3/{token}/{file_name}",
    name="generated-mp3",
    title="Generated MP3 audio",
    mime_type="audio/mpeg",
)
def generated_mp3(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="mp3")


@mcp.resource(
    "voxbridge://audio/wav/{token}/{file_name}",
    name="generated-wav",
    title="Generated WAV audio",
    mime_type="audio/wav",
)
def generated_wav(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="wav")


@mcp.resource(
    "voxbridge://audio/ogg/{token}/{file_name}",
    name="generated-ogg",
    title="Generated OGG audio",
    mime_type="audio/ogg",
)
def generated_ogg(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="ogg")


@mcp.resource(
    "voxbridge://audio/opus/{token}/{file_name}",
    name="generated-opus",
    title="Generated Opus audio",
    mime_type="audio/opus",
)
def generated_opus(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="opus")


@mcp.resource(
    "voxbridge://audio/aac/{token}/{file_name}",
    name="generated-aac",
    title="Generated AAC audio",
    mime_type="audio/aac",
)
def generated_aac(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="aac")


@mcp.resource(
    "voxbridge://audio/flac/{token}/{file_name}",
    name="generated-flac",
    title="Generated FLAC audio",
    mime_type="audio/flac",
)
def generated_flac(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="flac")


@mcp.resource(
    "voxbridge://audio/m4a/{token}/{file_name}",
    name="generated-m4a",
    title="Generated M4A audio",
    mime_type="audio/mp4",
)
def generated_m4a(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="m4a")


@mcp.resource(
    "voxbridge://audio/webm/{token}/{file_name}",
    name="generated-webm",
    title="Generated WebM audio",
    mime_type="audio/webm",
)
def generated_webm(token: str, file_name: str) -> bytes:
    return _read_audio_artifact(token, file_name, expected_format="webm")


def _build_delivery_result(
    result: SpeechResult,
    delivery: Literal["playback", "file", "both"],
    *,
    extra_metadata: dict[str, Any] | None = None,
) -> CallToolResult:
    _validate_delivery(delivery)
    if len(result.audio) > settings.voxbridge_max_audio_bytes:
        raise ToolError(
            f"Generated audio exceeds the {settings.voxbridge_max_audio_bytes:,}-byte limit"
        )
    if not result.mime_type.startswith("audio/"):
        raise ToolError("Provider returned an invalid audio media type")

    include_playback = delivery in {"playback", "both"}
    include_file = delivery in {"file", "both"}
    metadata = {
        **result.metadata,
        **(extra_metadata or {}),
        "synthetic_audio": True,
        "provider": result.provider,
        "model": result.model,
        "mime_type": result.mime_type,
        "request_id": result.request_id,
        "delivery": delivery,
        "playback_requested": include_playback,
        "inline_audio_included": delivery == "playback",
        "app_resource_playback": delivery == "both",
        "file_resource_included": include_file,
        "file_size_bytes": len(result.audio),
        "sha256": hashlib.sha256(result.audio).hexdigest(),
    }
    content: list[TextContent | AudioContent | ResourceLink] = []
    audio_content: AudioContent | None = None
    # ChatGPT can suppress a ResourceLink's host download action when the same
    # result also contains inline audio. In `both` mode the MCP App receives
    # playback bytes through hidden result metadata, leaving public content in
    # the proven downloadable-file shape.
    if delivery == "playback":
        audio_content = AudioContent(
            type="audio",
            data=base64.b64encode(result.audio).decode("ascii"),
            mimeType=result.mime_type,
        )

    file_resource: ResourceLink | None = None
    if include_file:
        format_id, extension, file_mime_type = _audio_file_details(result.mime_type)
        file_name = _download_filename(extension)
        try:
            token, artifact = _audio_artifacts.put(
                result.audio,
                mime_type=file_mime_type,
                format_id=format_id,
                file_name=file_name,
            )
        except ValueError as exc:
            raise ToolError(str(exc)) from exc
        resource_uri = _resource_uri(format_id, token, file_name)
        expires_at = (
            datetime.fromtimestamp(artifact.expires_at, tz=UTC).isoformat().replace("+00:00", "Z")
        )
        metadata.update(
            {
                "file_name": file_name,
                "file_mime_type": file_mime_type,
                "resource_uri": resource_uri,
                "materialize_resource_uri": _materialize_resource_uri(file_name),
                "materialize_max_bytes": settings.voxbridge_max_materialized_audio_bytes,
                "download_expires_at": expires_at,
            }
        )
        file_resource = ResourceLink(
            type="resource_link",
            uri=resource_uri,
            name=file_name,
            title=f"Download {file_name}",
            description="Short-lived downloadable synthetic audio generated by VoxBridge.",
            mimeType=file_mime_type,
            size=len(result.audio),
        )

    content.append(TextContent(type="text", text=json.dumps(metadata, ensure_ascii=False)))
    if audio_content is not None:
        content.append(audio_content)
    if file_resource is not None:
        content.append(file_resource)
    result_meta: dict[str, Any] | None = None
    if delivery == "both":
        # MCP tool-result metadata is delivered to the bound App but hidden from
        # the model. Supplying the same generated bytes here gives the App a
        # reliable playback path while the ResourceLink remains available for
        # standard resource reads and the host's native Download action.
        result_meta = {
            "voxbridge/audio": {
                "data": base64.b64encode(result.audio).decode("ascii"),
                "mimeType": metadata["file_mime_type"],
            }
        }
    return CallToolResult(content=content, structuredContent=metadata, meta=result_meta)


def _provider(provider: str):
    key = provider.strip().lower()
    if key not in REGISTRY:
        raise ToolError(f"Unknown provider '{provider}'. Use list_providers first.")
    p = REGISTRY[key]
    if not p.configured:
        raise ToolError(f"{p.display_name} is not connected on this VoxBridge gateway")
    return p


@mcp.tool(
    title="List voice providers",
    annotations=ToolAnnotations(
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
def list_providers() -> list[dict[str, Any]]:
    """List every VoxBridge provider, connection state, default model, and supported capabilities."""
    return [p.info() for p in REGISTRY.values()]


@mcp.tool(
    title="List provider voices",
    annotations=ToolAnnotations(
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
async def list_voices(
    provider: str, language: str | None = None, limit: int = 50
) -> list[dict[str, Any]]:
    """List voices from one provider. Use provider IDs from list_providers."""
    p = _provider(provider)
    try:
        voices = await p.list_voices(language=language, limit=max(1, min(limit, 100)))
    except ProviderError as exc:
        raise ToolError(str(exc)) from exc
    return [
        {
            "id": v.id,
            "name": v.name,
            "provider": v.provider,
            "language": v.language,
            "gender": v.gender,
            "description": v.description,
            "preview_url": v.preview_url,
            "metadata": v.metadata,
        }
        for v in voices
    ]


@mcp.tool(
    title="Generate realistic speech",
    meta={
        "ui": {"resourceUri": _AUDIO_DELIVERY_UI_URI},
        "openai/outputTemplate": _AUDIO_DELIVERY_UI_URI,
    },
    annotations=ToolAnnotations(
        readOnlyHint=False,
        destructiveHint=False,
        idempotentHint=False,
        openWorldHint=True,
    ),
)
@_replay_protected("generate_speech")
async def generate_speech(
    provider: str,
    text: str,
    voice_id: str | None = None,
    model: str | None = None,
    output_format: str = "mp3",
    instructions: str | None = None,
    speed: float | None = None,
    language: str | None = None,
    options_json: str | None = None,
    delivery: Literal["playback", "file", "both"] = "both",
    ctx: Context | None = None,
) -> Annotated[CallToolResult, SpeechDeliveryMetadata]:
    """Generate speech for playback, file download, or both from one provider call.

    `instructions` is provider-aware: Hume Octave 1 treats it as acting direction and
    OpenAI treats it as voice instructions on supported models. `options_json` is for
    documented provider-specific controls such as ElevenLabs stability/similarity,
    Cartesia emotion/volume, or Resemble HD synthesis. `playback` returns inline MCP audio;
    `file` returns a short-lived named resource; `both` gives the bound MCP App hidden
    playback bytes plus one file resource so compatible hosts retain their Download action.
    Raw PCM is not portable because it has no embedded sample metadata; request WAV instead.
    """
    if not text.strip():
        raise ToolError("text cannot be empty")
    _validate_delivery(delivery)
    normalized_output_format = output_format.strip().lower()
    if normalized_output_format == "pcm":
        raise ToolError(
            "PCM delivery is unavailable in this developer alpha because raw PCM does not "
            "carry portable sample metadata; use WAV instead"
        )
    if len(text) > settings.voxbridge_max_text_chars:
        raise ToolError(
            f"text exceeds the {settings.voxbridge_max_text_chars:,}-character "
            "developer-alpha limit"
        )
    options = _parse_options_json(options_json)
    p = _provider(provider)
    request = SpeechRequest(
        text=text,
        voice_id=voice_id,
        model=model,
        output_format=normalized_output_format,
        instructions=instructions,
        speed=speed,
        language=language,
        options=options,
    )
    try:
        p.validate_request(request)
        async with _generation_slots:
            result = await p.generate(request)
        p.validate_audio(result.audio)
    except ProviderError as exc:
        raise ToolError(str(exc)) from exc
    return _build_delivery_result(result, delivery)


@mcp.tool(
    title="Generate multi-voice dialogue",
    meta={
        "ui": {"resourceUri": _AUDIO_DELIVERY_UI_URI},
        "openai/outputTemplate": _AUDIO_DELIVERY_UI_URI,
    },
    annotations=ToolAnnotations(
        readOnlyHint=False,
        destructiveHint=False,
        idempotentHint=False,
        openWorldHint=True,
    ),
)
@_replay_protected("generate_dialogue")
async def generate_dialogue(
    provider: str,
    segments: Annotated[list[DialogueSegment], Field(min_length=2, max_length=10)],
    model: str | None = None,
    language: str | None = None,
    delivery: Literal["playback", "file", "both"] = "both",
    ctx: Context | None = None,
) -> Annotated[CallToolResult, SpeechDeliveryMetadata]:
    """Generate ordered voice turns and join them into one PCM WAV file.

    Each segment selects its own `voice_id`, text, performance controls, and
    pause. All segments use one provider and optional global model. VoxBridge
    performs schema and shared provider-capability validation before generation,
    then synthesizes sequentially and joins compatible PCM audio without a lossy
    transcode. A provider can still reject a later segment after earlier calls
    completed. The final pause is ignored. Delivery supports playback, file, or
    both, just like generate_speech.
    """

    _validate_delivery(delivery)
    if len(segments) < 2:
        raise ToolError("segments must include at least two voice turns")
    if len(segments) > settings.voxbridge_max_dialogue_segments:
        raise ToolError(
            f"segments exceeds the {settings.voxbridge_max_dialogue_segments}-turn limit"
        )
    total_chars = sum(len(segment.text) for segment in segments)
    if total_chars > settings.voxbridge_max_dialogue_chars:
        raise ToolError(
            f"dialogue exceeds the {settings.voxbridge_max_dialogue_chars:,}-character limit"
        )
    pause_total_ms = sum(segment.pause_after_ms for segment in segments[:-1])
    if pause_total_ms > settings.voxbridge_max_dialogue_pause_ms:
        raise ToolError(
            "dialogue pauses exceed the "
            f"{settings.voxbridge_max_dialogue_pause_ms:,}-millisecond limit"
        )

    p = _provider(provider)
    requests: list[SpeechRequest] = []
    for index, segment in enumerate(segments, start=1):
        request = SpeechRequest(
            text=segment.text,
            voice_id=segment.voice_id,
            model=model,
            output_format="wav",
            instructions=segment.instructions,
            speed=segment.speed,
            language=segment.language or language,
            options=segment.options,
        )
        try:
            p.validate_request(request)
        except ProviderError as exc:
            raise ToolError(f"Segment {index} is invalid: {exc}") from exc
        requests.append(request)

    composer = PcmWavComposer(
        max_pcm_bytes=max(1, settings.voxbridge_max_audio_bytes - 44),
        max_duration_seconds=settings.voxbridge_max_dialogue_duration_seconds,
    )
    request_ids: list[str | None] = []
    provider_call_count = 0
    provider_call_attempts = 0
    try:
        async with _generation_slots:
            for index, (request, segment) in enumerate(
                zip(requests, segments, strict=True),
                start=1,
            ):
                provider_call_attempts += 1
                try:
                    segment_result = await p.generate(request)
                    provider_call_count += 1
                    p.validate_audio(segment_result.audio)
                except ProviderError as exc:
                    raise ToolError(
                        _dialogue_failure_message(
                            index,
                            len(segments),
                            provider_call_count,
                            provider_call_attempts,
                            str(exc),
                        )
                    ) from exc
                except Exception as exc:
                    raise ToolError(
                        _dialogue_failure_message(
                            index,
                            len(segments),
                            provider_call_count,
                            provider_call_attempts,
                            "the provider adapter failed unexpectedly",
                        )
                    ) from exc
                if segment_result.mime_type.partition(";")[0].strip().lower() not in {
                    "audio/wav",
                    "audio/x-wav",
                    "audio/vnd.wave",
                }:
                    raise ToolError(
                        _dialogue_failure_message(
                            index,
                            len(segments),
                            provider_call_count,
                            provider_call_attempts,
                            "the provider did not return PCM WAV audio",
                        )
                    )
                try:
                    composer.append(
                        WavSegment(
                            segment_result.audio,
                            segment.pause_after_ms if index < len(segments) else 0,
                        ),
                        segment_number=index,
                    )
                except AudioCompositionError as exc:
                    raise ToolError(
                        _dialogue_failure_message(
                            index,
                            len(segments),
                            provider_call_count,
                            provider_call_attempts,
                            str(exc),
                        )
                    ) from exc
                except Exception as exc:
                    raise ToolError(
                        _dialogue_failure_message(
                            index,
                            len(segments),
                            provider_call_count,
                            provider_call_attempts,
                            "WAV assembly failed unexpectedly",
                        )
                    ) from exc
                request_ids.append(segment_result.request_id)
        composed_audio = composer.finish()
    except BaseException:
        composer.close()
        raise

    parameters = composer.parameters
    assert parameters is not None
    channels, sample_width, frame_rate = parameters

    composed = SpeechResult(
        audio=composed_audio,
        mime_type="audio/wav",
        provider=p.id,
        model=model or p.default_model,
        metadata={
            "dialogue": True,
            "segment_count": len(segments),
            "voice_ids": [segment.voice_id for segment in segments],
            "total_characters": total_chars,
            "pause_total_ms": pause_total_ms,
            "provider_call_count": provider_call_count,
            "duration_seconds": composer.duration_seconds,
            "source_format": {
                "channels": channels,
                "sample_width_bytes": sample_width,
                "sample_rate_hz": frame_rate,
            },
            "segment_request_ids": request_ids,
        },
    )
    try:
        return _build_delivery_result(composed, delivery)
    except ToolError as exc:
        raise ToolError(
            "Dialogue generation completed, but final delivery failed after "
            f"{provider_call_count} provider calls. Provider charges may already apply; "
            f"no combined audio file was stored. {exc}"
        ) from exc
    except Exception as exc:
        raise ToolError(
            "Dialogue generation completed, but final delivery failed after "
            f"{provider_call_count} provider calls. Provider charges may already apply; "
            "no combined audio file was stored."
        ) from exc


@mcp.tool(
    title="Prepare generated audio attachment",
    meta={
        "ui": {"visibility": ["model", "app"]},
        "openai/widgetAccessible": True,
        "openai/toolInvocation/invoking": "Preparing exact audio attachment…",
        "openai/toolInvocation/invoked": "Audio attachment prepared",
    },
    annotations=ToolAnnotations(
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=False,
    ),
)
def materialize_audio_file(
    resource_uri: Annotated[
        str | None,
        Field(
            min_length=1,
            max_length=512,
            description=(
                "Use the exact materialize_resource_uri returned by generate_speech or "
                "generate_dialogue. The longer resource_uri is also accepted. Omit this "
                "when using the exact generated file_name fallback."
            ),
        ),
    ] = None,
    file_name: Annotated[
        str | None,
        Field(
            min_length=1,
            max_length=128,
            description=(
                "Fallback for hosts that hide materialize_resource_uri: use the exact "
                "file_name returned by generate_speech or generate_dialogue. Never infer, "
                "alter, or supply a path. Omit this when resource_uri is available."
            ),
        ),
    ] = None,
) -> Annotated[CallToolResult, MaterializedAudioMetadata]:
    """Return a generated audio resource as an embedded binary file.

    Supply exactly one locator. Prefer the exact `materialize_resource_uri` from
    generate_speech or generate_dialogue; if the host hides that custom URI, use the
    exact generated `file_name`. The longer `resource_uri` is retained as a
    backward-compatible input. Call this only when an MCP client or compatible
    downstream tool explicitly accepts embedded resources. This tool only returns the
    embedded resource; an MCP App must separately pass it through
    `ui/update-model-context` before a compatible ChatGPT host adds it to the message
    composer. Other hosts may present it differently. The ordinary ResourceLink remains
    the efficient download path; this bounded, opt-in result avoids embedding every audio
    file.
    """

    if (resource_uri is None) == (file_name is None):
        raise ToolError("Provide exactly one of resource_uri or file_name")
    if resource_uri is not None:
        artifact = _artifact_from_resource_uri(resource_uri)
        source_resource_uri = resource_uri
    else:
        assert file_name is not None  # narrowed by the exactly-one check above
        artifact = _artifact_from_file_name(file_name)
        source_resource_uri = _materialize_resource_uri(artifact.file_name)
    if len(artifact.data) > settings.voxbridge_max_materialized_audio_bytes:
        raise ToolError(
            "Audio file is too large for inline tool handoff; use Download when the host "
            "offers it, or generate a shorter file"
        )
    file_uri = f"file:///{quote(artifact.file_name, safe='')}"
    metadata = {
        "synthetic_audio": True,
        "materialized": True,
        "file_name": artifact.file_name,
        "file_mime_type": artifact.mime_type,
        "file_size_bytes": len(artifact.data),
        "sha256": hashlib.sha256(artifact.data).hexdigest(),
        "source_resource_uri": source_resource_uri,
    }
    embedded = EmbeddedResource(
        type="resource",
        resource=BlobResourceContents(
            uri=file_uri,
            mimeType=artifact.mime_type,
            blob=base64.b64encode(artifact.data).decode("ascii"),
        ),
    )
    return CallToolResult(
        content=[
            TextContent(type="text", text=json.dumps(metadata, ensure_ascii=False)),
            embedded,
        ],
        structuredContent=metadata,
    )


async def _health(_: Request) -> JSONResponse:
    return JSONResponse({"status": "ok", "service": "voxbridge", "version": __version__})


async def _ready(_: Request) -> JSONResponse:
    configured = sorted(provider.id for provider in REGISTRY.values() if provider.configured)
    status = 200 if configured else 503
    return JSONResponse(
        {"status": "ready" if configured else "not_ready", "providers": configured},
        status_code=status,
    )


def build_http_app():
    transport_security = TransportSecuritySettings(
        enable_dns_rebinding_protection=True,
        allowed_hosts=settings.voxbridge_allowed_hosts,
        allowed_origins=settings.voxbridge_allowed_origins,
    )
    app = mcp.streamable_http_app(
        streamable_http_path="/mcp",
        json_response=True,
        stateless_http=True,
        max_request_body_size=64 * 1024,
        transport_security=transport_security,
        host=settings.voxbridge_host,
    )
    app.router.routes.insert(0, Route("/healthz", _health, methods=["GET"]))
    app.router.routes.insert(1, Route("/readyz", _ready, methods=["GET"]))
    return app


def main() -> None:
    if settings.voxbridge_transport == "stdio":
        mcp.run(transport="stdio")
        return
    settings.assert_safe_bind()
    app = build_http_app()
    uvicorn.run(
        app,
        host=settings.voxbridge_host,
        port=settings.voxbridge_port,
        log_level=settings.voxbridge_log_level.lower(),
    )


if __name__ == "__main__":
    main()
